### ISSUE TITLE
how to get api key

### ISSUE THREAD

**Issue by manishkumar1601** [Krakinz/Corlexa#4]
Top Secret KrakinzLab API key!

Your Localized Postsqldb API Link!

how to get this 2 api keys?

**Comment by Krakinz** [comment]
![image](https://user-images.githubusercontent.com/87024922/152992026-a9acef1d-0d6d-4042-a844-544d2c0e7563.png)


If I Make It Public Again, Codes Will Be Given In My TelegramBot!

**Comment by manishkumar1601** [comment]
Okay bro Thank you ❤❤...... can i have your number?... im also making a bot and also md bot thatswhy ... for help... you can send me message on my instagram its on my github profile...

**Comment by Krakinz** [comment]
> Okay bro Thank you ❤❤...... can i have your number?... im also making a bot and also md bot thatswhy ... for help... you can send me message on my instagram its on my github profile...

You Can Ping Me In Our Corlexa Whatsapp GC. MD is still not ready properly but sure you can go ahead.
